--[[
    init.lua
    Created: 05/28/2025 12:14:12
    Description: Autogenerated script file for the map mt_bristle.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local mt_bristle = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---mt_bristle.Init(zone)
--Engine callback function
function mt_bristle.Init(zone)


end

---mt_bristle.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function mt_bristle.EnterSegment(zone, rescuing, segmentID, mapID)


end

---mt_bristle.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function mt_bristle.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---mt_bristle.Rescued(zone, name, mail)
--Engine callback function
function mt_bristle.Rescued(zone, name, mail)


end

return mt_bristle

