--[[
    init.lua
    Created: 05/30/2025 16:49:04
    Description: Autogenerated script file for the map sunset_view.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local sunset_view = {}

-------------------------------
-- Map Callbacks
-------------------------------
---sunset_view.Init(map)
--Engine callback function
function sunset_view.Init(map)


end

---sunset_view.Enter(map)
--Engine callback function
function sunset_view.Enter(map)

    GROUND:Hide("PLAYER")

    if SV.Progression.Chapter == 1 then
      --sunset view
		  GAME:FadeIn(60)

		  --bubbles
		
		  GAME:WaitFrames(240)
		  GAME:FadeOut(false, 60)

      GAME:EnterGroundMap("dusk_beach", "Entrance", true)
    end


end

---sunset_view.Exit(map)
--Engine callback function
function sunset_view.Exit(map)


end

---sunset_view.Update(map)
--Engine callback function
function sunset_view.Update(map)


end

---sunset_view.GameSave(map)
--Engine callback function
function sunset_view.GameSave(map)


end

---sunset_view.GameLoad(map)
--Engine callback function
function sunset_view.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return sunset_view

