--[[
    init.lua
    Created: 05/28/2025 18:10:13
    Description: Autogenerated script file for the map mt_bristle_peak.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local mt_bristle_peak = {}

-------------------------------
-- Map Callbacks
-------------------------------
---mt_bristle_peak.Init(map)
--Engine callback function
function mt_bristle_peak.Init(map)


end

---mt_bristle_peak.Enter(map)
--Engine callback function
function mt_bristle_peak.Enter(map)

  GAME:FadeIn(20)

end

---mt_bristle_peak.Exit(map)
--Engine callback function
function mt_bristle_peak.Exit(map)


end

---mt_bristle_peak.Update(map)
--Engine callback function
function mt_bristle_peak.Update(map)


end

---mt_bristle_peak.GameSave(map)
--Engine callback function
function mt_bristle_peak.GameSave(map)


end

---mt_bristle_peak.GameLoad(map)
--Engine callback function
function mt_bristle_peak.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return mt_bristle_peak

