--[[
    init.lua
    Created: 05/30/2025 16:26:11
    Description: Autogenerated script file for the map krabby_scene_a.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local krabby_scene_a = {}

-------------------------------
-- Map Callbacks
-------------------------------
---krabby_scene_a.Init(map)
--Engine callback function
function krabby_scene_a.Init(map)


end

---krabby_scene_a.Enter(map)
--Engine callback function
function krabby_scene_a.Enter(map)

  GROUND:Hide("PLAYER")

  -- iirc these scenes only show up in chapters 1 and 20 so we're probably fine to just leave it like this

  --krabby 1
		GAME:FadeIn(60)
		--bubbles
		GAME:WaitFrames(120)
		GAME:FadeOut(false, 60)

    GAME:EnterGroundMap("krabby_scene_b", "Entrance")

end

---krabby_scene_a.Exit(map)
--Engine callback function
function krabby_scene_a.Exit(map)


end

---krabby_scene_a.Update(map)
--Engine callback function
function krabby_scene_a.Update(map)


end

---krabby_scene_a.GameSave(map)
--Engine callback function
function krabby_scene_a.GameSave(map)


end

---krabby_scene_a.GameLoad(map)
--Engine callback function
function krabby_scene_a.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return krabby_scene_a

