--[[
    init.lua
    Created: 12/04/2023 12:47:19
    Description: Autogenerated script file for the map storm_cutscene_c.
]]--
-- Commonly included lua functions and data
require 'eos.common'

-- Package name
local storm_cutscene_c = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---storm_cutscene_c.Init(map)
--Engine callback function
function storm_cutscene_c.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---storm_cutscene_c.Enter(map)
--Engine callback function
function storm_cutscene_c.Enter(map)

  GAME:CutsceneMode(true)
  GROUND:Hide("PLAYER")

  -- set camera position
  GAME:MoveCamera(160, 120, 1, false)

  -- hide initial objects
  GROUND:Hide("BluffFlash")
  GROUND:Hide("LightningA")
  GROUND:Hide("LightningB")
  GROUND:Hide("LightningC")

  GAME:FadeIn(120)
  
  GAME:WaitFrames(90)
  
  --lightning strike
  SOUND:PlaySE("Battle/EVT_CH01_Thunder")
  GROUND:Unhide("BluffFlash")

  GAME:WaitFrames(2)
  
  GROUND:Hide("BluffFlash")
  
  GAME:WaitFrames(2)
  
  GROUND:Unhide("BluffFlash")
  
  GAME:WaitFrames(2)

  GROUND:Unhide("LightningA")

  GAME:WaitFrames(2)

  GROUND:Hide("LightningA")
  GROUND:Unhide("LightningB")

  GAME:WaitFrames(4)

  GROUND:Hide("LightningB")
  GROUND:Unhide("LightningC")

  GAME:WaitFrames(10)

  GROUND:Hide("LightningC")

  GAME:WaitFrames(2)

  GROUND:Hide("BluffFlash")
  
  GAME:WaitFrames(90)
  
  --lightning strike
  SOUND:PlaySE("Battle/EVT_CH01_Thunder")
  GROUND:Unhide("BluffFlash")

  GAME:WaitFrames(2)
  
  GROUND:Hide("BluffFlash")
  
  GAME:WaitFrames(2)
  
  GROUND:Unhide("BluffFlash")
  
  GAME:WaitFrames(2)

  GROUND:Unhide("LightningA")

  GAME:WaitFrames(2)

  GROUND:Hide("LightningA")
  GROUND:Unhide("LightningB")

  GAME:WaitFrames(4)

  GROUND:Hide("LightningB")
  GROUND:Unhide("LightningC")

  GAME:WaitFrames(10)

  GROUND:Hide("LightningC")

  GAME:WaitFrames(2)

  GROUND:Hide("BluffFlash")
  
  GAME:WaitFrames(90)
  
  --fade out
  local coro1 = TASK:BranchCoroutine(function() GAME:FadeOut(false, 120) end)
  local coro2 = TASK:BranchCoroutine(function() SOUND:FadeOutSE("Ambient/AMB_Storm", 120) end)
  TASK:JoinCoroutines({coro1, coro2})
  
  --next scene
  GAME:EnterZone('hub', -1, 1, 1)

end

---storm_cutscene_c.Exit(map)
--Engine callback function
function storm_cutscene_c.Exit(map)


end

---storm_cutscene_c.Update(map)
--Engine callback function
function storm_cutscene_c.Update(map)


end

---storm_cutscene_c.GameSave(map)
--Engine callback function
function storm_cutscene_c.GameSave(map)


end

---storm_cutscene_c.GameLoad(map)
--Engine callback function
function storm_cutscene_c.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return storm_cutscene_c

