--[[
    init.lua
    Created: 05/30/2025 16:26:11
    Description: Autogenerated script file for the map krabby_scene_b.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local krabby_scene_b = {}

-------------------------------
-- Map Callbacks
-------------------------------
---krabby_scene_b.Init(map)
--Engine callback function
function krabby_scene_b.Init(map)


end

---krabby_scene_b.Enter(map)
--Engine callback function
function krabby_scene_b.Enter(map)

  GROUND:Hide("PLAYER")

  -- iirc these scenes only show up in chapters 1 and 20 so we're probably fine to just leave it like this

  --krabby 2 & play bgm
		SOUND:PlayBGM("004 - On the Beach at Dusk.ogg", true)
		
    GAME:FadeIn(60)
		--bubbles
		GAME:WaitFrames(120)
		GAME:FadeOut(false, 60)

    GAME:EnterGroundMap("dusk_beach", "Entrance", true)

end

---krabby_scene_b.Exit(map)
--Engine callback function
function krabby_scene_b.Exit(map)


end

---krabby_scene_b.Update(map)
--Engine callback function
function krabby_scene_b.Update(map)


end

---krabby_scene_b.GameSave(map)
--Engine callback function
function krabby_scene_b.GameSave(map)


end

---krabby_scene_b.GameLoad(map)
--Engine callback function
function krabby_scene_b.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return krabby_scene_b

